### ISSUE TITLE
When using 'path' Editor prop, model undo data is preserved after dispose

### ISSUE THREAD

**Issue by tuckbarber** [suren-atoyan/monaco-react#305]
**Describe the bug**
When either the `defaultPath` or `path` props are provided to the `Editor` component, it seems that the model "undostack" is preserved even after the editor component being unmounted and the `.getModel().dispose()` method being explicitly called on the editor ref. If a new model is created with the same `path`, I am able to undo/redo even though it should be a new instance.

**To Reproduce**
I have an editor wrapper component called `CodeEditor` that wraps around the monaco-react `Editor` component and provides the Editor with a `defaultPath` of a file being loaded so that Monaco will automatically highlighted based on the detected extension language. 

This is within a file browsing app context so one file with a path will be loaded via API and viewed in a modal containing `<CodeEditor>`, and then when that modal is closed `<CodeEditor>` is unmounted (and that model should be destroyed) until another file is opened.

All code within one `CodeEditor.tsx` file, the simplified component would look like

```jsx
return(
  <Editor
      defaultValue={props.defaultValue}
      defaultPath={props.filename}
      onMount={handleEditorDidMount}
  />
)
```
The handling of mounting of the Editor looks like:

```jsx
const editorRef = useRef(null);

const handleEditorDidMount = (editor) => {
    editorRef.current = editor;
};
```
And the component is unmounted
```jsx
useEffect(() => {
    return () => {
        // all three is likely overkill, but it seems one of them should clear it
        editorRef.current.getModel().dispose();
        editorRef.current.setModel(null);
        editorRef.current.dispose();
    };
}, []);
```

The problem comes when I 
1. open a file (`defaultPath="pathA"`)
2. make changes
3. close editor / save file to the server (`.getModel().dispose()` called)
4. open same file (`defaultPath="pathA"` again)

 I can undo/redo as though it is the same model instance. Using `console.log(editorRef.current.getModel().id)` I can see a new model with a new id is being used each file load. 

If I remove `defaultPath` this undo/redo data saving issue no longer occurs, but I lose the language highlighting based on the extension.

**Expected behavior**
I would expect that the model data would be cleared using `editorRef.current.getModel().dispose();`

**Desktop:**
 - OS: macOS
 - Browser: Chrome 95.0.4638.54
 - Version: @monaco-editor/react 4.3.1

**Comment by suren-atoyan** [comment]
Hello @tuckbarber. could you please create a reproducible [codesandbox](https://codesandbox.io/) that we will be able to check? It should have been working by the way; if the editor is being unmounted the model should be disposed of, check [this](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L197). There are properties `keepCurrentModel` and `saveViewState` to keep the model after unmount and save the view state (+ undo/redo stack)

**Comment by tuckbarber** [comment]
Hi @suren-atoyan, thanks for replying!

I also thought that simply unmounting the editor should be enough to dispose as `keepCurrentModel` is false by default, I just had the other dispose calls to be certain... however, unless I'm missing something, I don't seeing that happen

e.g.  [example codesandbox](https://codesandbox.io/s/bitter-silence-cys77?file=/src/CodeEditor.tsx)

Hopefully this codesandbox lays it out clear enough
To reproduce:
1. Open file and made edits
2. Close file
3. Open file again

Cmd+Z still has an effect. However, if you remove the `defaultPath={props.filename}` line from `Editor` this problem no longer happens.

Am I missing something?

**Comment by gungorerhan** [comment]
I am facing the same issue even if I don't use the `defaultPath` prop.

**Comment by maleksandar** [comment]
Hi all! This is still not fixed, because I can still reproduce this issue.
